# Basic Functions in Python

This notebook writes functions in python to solve different problems.
I solve three problems in this notebook to illustrate my understanding of how to use functions in python.  

---
# Functions

- Functions are declared with the keyword `def`.

- Arguments can be defined with **or** without default values.

- Functions must explicitly include a `return` statement to return a value.

In [23]:
def f(x):
    return x+2

---
# &diams; Functions  Problem-1 : Scores to Grades

**Task-1** Write a function to assign grades to a student such that
```
A = [90 - 100]
B = [80 - 90)
C = [70 - 80)
D = [60 - 70)
F = [0, 60)
```
where square brackets indicate inclusive boundaries and parentheses indicate exclusive boundaries.

In [24]:
scores = [ 84,  76,  67,  23,  83,  23,  50, 100,  32,  84,  22,  41,  27,
        29,  71,  85,  47,  77,  39,  25,  85,  69,  22,  66, 100,  92,
        97,  46,  81,  88,  67,  20,  52,  62,  39,  36,  79,  54,  74,
        64,  33,  68,  85,  69,  84,  30,  68, 100,  71,  33,  21,  95,
        92,  72,  53,  50,  31,  82,  53,  68,  49,  37,  40,  21,  94,
        30,  54,  58,  92,  95,  73,  80,  81,  56,  44,  22,  69,  70,
        25,  50,  59,  32,  65,  79,  27,  62,  27,  31,  78,  88,  68,
        53,  79,  69,  89,  38,  80,  55,  92,  55]

In [25]:
# ANSWER 
def score_to_grade(score):
    if score >= 90 and score <= 100: #A = [90 - 100]
        return "A"
    elif score >= 80 and score < 90: #B = [80 - 90)
        return "B"
    elif score >= 70 and score < 80:
        return "C"
    elif score >= 60 and score < 70:
        return "D"
    else:
        return "F"

In [26]:
#using a for loop and a function score_to_grade() we are converting a list of numeric scores to a list of grades
grades = []
for score in scores:
    grades.append(score_to_grade(score))
print(grades)

['B', 'C', 'D', 'F', 'B', 'F', 'F', 'A', 'F', 'B', 'F', 'F', 'F', 'F', 'C', 'B', 'F', 'C', 'F', 'F', 'B', 'D', 'F', 'D', 'A', 'A', 'A', 'F', 'B', 'B', 'D', 'F', 'F', 'D', 'F', 'F', 'C', 'F', 'C', 'D', 'F', 'D', 'B', 'D', 'B', 'F', 'D', 'A', 'C', 'F', 'F', 'A', 'A', 'C', 'F', 'F', 'F', 'B', 'F', 'D', 'F', 'F', 'F', 'F', 'A', 'F', 'F', 'F', 'A', 'A', 'C', 'B', 'B', 'F', 'F', 'F', 'D', 'C', 'F', 'F', 'F', 'F', 'D', 'C', 'F', 'D', 'F', 'F', 'C', 'B', 'D', 'F', 'C', 'D', 'B', 'F', 'B', 'F', 'A', 'F']

---
**Task-2** Suppose the instructor has an attendance policy: studens whose attendance is 10 days or fewer get their grade reduced by one (A to B, B to C, C to D, D to F, and F stays F). 
Write a new function that take a score and an attendance as an argument and return A, B, C, D, or F as appropriate.

In [27]:
attendances = [13,  1, 19, 14, 17, 10,  1,  5, 16,  6, 12, 15,  7, 20,  3,  9,  7,
        2, 11,  7, 12,  8, 19, 18, 10, 12,  1,  1, 13,  3, 20,  7, 10, 13,
       10,  7,  7,  9,  1, 12,  2, 12,  6, 16, 14,  9,  4, 16, 16,  5, 13,
       20, 11, 20,  4, 10, 11, 14,  6,  5,  9, 17, 17,  3, 18, 18, 17,  5,
       18, 19, 13,  2,  0, 11, 16,  5, 11,  1,  0,  0,  9, 20,  7, 11, 15,
        2,  1, 15, 18, 15, 20, 18, 17, 16,  5, 16, 20,  5, 18,  1]

In [28]:
# ANSWER 
def score_and_attendance_to_grade(score, attendance):
    grade = score_to_grade(score)
    if attendance <= 10:
        if grade == 'A':
            return 'B'
        elif grade == 'B':
            return 'C'
        elif grade == 'C':
            return 'D'
        elif grade == 'D':
            return 'F'
    return grade

In [29]:
grades = []
for score, attendance in zip(scores, attendances):
    grades.append(score_and_attendance_to_grade(score, attendance))
print(grades)

['B', 'D', 'D', 'F', 'B', 'F', 'F', 'B', 'F', 'C', 'F', 'F', 'F', 'F', 'D', 'C', 'F', 'D', 'F', 'F', 'B', 'F', 'F', 'D', 'B', 'A', 'B', 'F', 'B', 'C', 'D', 'F', 'F', 'D', 'F', 'F', 'D', 'F', 'D', 'D', 'F', 'D', 'C', 'D', 'B', 'F', 'F', 'A', 'C', 'F', 'F', 'A', 'A', 'C', 'F', 'F', 'F', 'B', 'F', 'F', 'F', 'F', 'F', 'F', 'A', 'F', 'F', 'F', 'A', 'A', 'C', 'C', 'C', 'F', 'F', 'F', 'D', 'D', 'F', 'F', 'F', 'F', 'F', 'C', 'F', 'F', 'F', 'F', 'C', 'B', 'D', 'F', 'C', 'D', 'C', 'F', 'B', 'F', 'A', 'F']

---
**Task-3** Using the resulting grades from part (b), count the number of students with each grade.

In [30]:
# ANSWER 
def count_grades(grades):
    grade_count = {'A': 0, 'B': 0, 'C': 0, 'D': 0, 'F': 0}
    for grade in grades:
        grade_count[grade] += 1
    return grade_count

grades = ['B', 'D', 'D', 'F', 'B', 'F', 'F', 'B', 'F', 'C', 'F', 'F', 'F', 'F', 'D', 'C', 'F', 'D', 'F', 'F', 'B', 'F', 'F', 'D', 'B', 'A', 'B', 'F', 'B', 'C', 'D', 'F', 'F', 'D', 'F', 'F', 'D', 'F', 'D', 'D', 'F', 'D', 'C', 'D', 'B', 'F', 'F', 'A', 'C', 'F', 'F', 'A', 'A', 'C', 'F', 'F', 'F', 'B', 'F', 'F', 'F', 'F', 'F', 'F', 'A', 'F', 'F', 'F', 'A', 'A', 'C', 'C', 'C', 'F', 'F', 'F', 'D', 'D', 'F', 'F', 'F', 'F', 'F', 'C', 'F', 'F', 'F', 'F', 'C', 'B', 'D', 'F', 'C', 'D', 'C', 'F', 'B', 'F', 'A', 'F']

grade_count = count_grades(grades)

for grade, count in grade_count.items():
    print(grade, count)

A 8
B 11
C 13
D 16
F 52

---
# &diams; Functions Problem 2 :  Prime Numbers 


**Task-1** Write a function `is_prime(n)` that returns `True` only if n is prime.

In [31]:
# ANSWER
#is_prime(n) used to see if a given integer n is prime or not.
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

In [32]:
# testing
## The expected output: 1 - False; 21 - False; 41 - True
print("1-", is_prime(1))
print("21-",is_prime(21))
print("41-",is_prime(41))

1- False
21- False
41- True

In [33]:
# testing speed
%%timeit
is_prime(100000)

566 ns ± 11.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

---
**Task-2** Note that apart from 2 and 3, all primes are of the form 6k ± 1 (though not all numbers of the form 6k ± 1 are prime of course). Using this, we can improve the computation time approx. by a factor of 3. Write a new function `is_prime_fast(n)` to use this strategy.

In [34]:
#ANSWER
def is_prime_fast(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

In [35]:
# testing
## The expected output: 1 - False; 21 - False; 41 - True
print("1-",is_prime(1))
print("21-",is_prime(21))
print("41-",is_prime(41))

1- False
21- False
41- True

In [36]:
# testing speed
%%timeit
is_prime_fast(100000)

206 ns ± 14.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

---
**Task-3** Write a function `all_primes(n)` that returns a list of all primes up to n.

In [37]:
# ANSWER
def all_primes(n):
    primes = []
    for i in range(2, n + 1):
        if is_prime_fast(i):
            primes.append(i)
    return primes

In [38]:
# testing
## the expected output is [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59]
print(all_primes(59))

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59]

# --- 
**Task-4** Write a function `first_n_primes(n)` that returns the first n primes in a list.

In [39]:
# ANSWER
def first_n_primes(n):
    primes = []
    num = 2
    while len(primes) < n:
        if is_prime_fast(num):
            primes.append(num)
        num += 1
    return primes

In [40]:
# testing
## the expected output is [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]
print(first_n_primes(10))

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

---
**Task-5** Use list comprehension to generate a list with elements i + j with both i and j are prime and 0 < i < j < 15.

The expected output is,
```
[5, 7, 9, 13, 15, 8, 10, 14, 16, 12, 16, 18, 18, 20, 24]
```

In [41]:
# ANSWER
[i + j for i in range(2, 15) for j in range(i+1, 15) if is_prime(i) and is_prime(j)]

[5, 7, 9, 13, 15, 8, 10, 14, 16, 12, 16, 18, 18, 20, 24]

---
**Task-6 : Lambda Function** Write the function `all_primes_lamda(n)` that return a list with all prime numbers up to n using three (or less) lines of code. Do not use any functions that you have defined in the previously questions.

In [42]:
# ANSWER
all_primes_lambda = lambda n: [x for x in range(2, n+1) if all(x % y != 0 for y in range(2, int(x**0.5)+1))]

In [43]:
# testing
## the expected output is [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59]
print(all_primes_lambda(59))

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59]

---
# &diams; Functions Problem 3:  Collatz sequences 

Collatz conjecture: http://en.wikipedia.org/wiki/Collatz_conjecture

The following iterative sequence is defined for the set of positive integers:
- n → n/2 (n is even)
- n → 3n + 1 (n is odd)

Using the rule above and starting with 13, we generate the following sequence:

13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1

It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.

**Task-1** Write a function `collatz_seq(n)` using iteration, save the sequence in a list.

In [44]:
# ANSWER
def collatz_seq(n):
    seq = [n]
    while n != 1:
        if n % 2 == 0:
            n = n // 2
        else:
            n = 3 * n + 1
        seq.append(n)
    return seq

In [45]:
# testing
## the expected output is [13, 40, 20, 10, 5, 16, 8, 4, 2, 1]
print(collatz_seq(13))

[13, 40, 20, 10, 5, 16, 8, 4, 2, 1]

---
**Task-2** Write another function `collatz_seq2(n)` using recursion, save the sequence in a list.

In [46]:
#ANSWER- #the function checks if n is equal to 1
def collatz_seq2(n, seq=None):
    if seq is None:
        seq = []
    seq.append(n)
    if n == 1:
        return seq
    else:
        if n % 2 == 0:
            return collatz_seq2(n // 2, seq)
        else:
            return collatz_seq2(3 * n + 1, seq)

In [47]:
# testing
## expected output [13, 40, 20, 10, 5, 16, 8, 4, 2, 1]
print(collatz_seq2(13))

[13, 40, 20, 10, 5, 16, 8, 4, 2, 1]

---
**Task-3** Which starting number, under one million, produces the longest chain? What is the length of the longest chain?

NOTE: Once the chain starts the terms are allowed to go above one million.

The expected answer is, 837799 produces the longest chain of length 525.

In [22]:
# ANSWER
#The expected answer is, 837799 produces the longest chain of length 525.
def collatz_length(n):
    length = 1
    while n!= 1:
        if n % 2 == 0:
            n = n // 2
        else:
            n = 3 * n + 1
        length += 1
    return length

    
def longest_collatz(limit):
    max_length = 0
    max_start = 0
    for i in range(1, limit):
        length = collatz_length(i)
        if length > max_length:
            max_length = length
            max_start = i
    return max_start, max_length
print(longest_collatz(1000000))

(837799, 525)